services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    env_file:
      - .env
    volumes:
      - ${PWD}/data/postgres:/data/postgres
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - ${PWD}/data/redis:/data
